logging:
    level:
        org.vld.batch: DEBUG

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/people
        username: family
        password: family
        driverClassName: org.postgresql.Driver
