logging:
    level:
        org.vld.batch: DEBUG

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/people
        username: postgres
        password: Password1!
        driverClassName: org.postgresql.Driver

spring.batch.initialize-schema: always
spring.batch.job.names: splitHumansJob